edition = "2024"

max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

reorder_imports = true
reorder_modules = true

use_small_heuristics = "Default"
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
remove_nested_parens = true
merge_derives = true